# Python stubs generated by omniidl from Irrigation.idl
# DO NOT EDIT THIS FILE!
#######################
import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "SDR"
#
__name__ = "SDR"
_0_SDR = omniORB.openModule("SDR", r"Irrigation.idl")
_0_SDR__POA = omniORB.openModule("SDR__POA", r"Irrigation.idl")


# interface CapteurData
_0_SDR._d_CapteurData = (omniORB.tcInternal.tv_objref, "IDL:SDR/CapteurData:1.0", "CapteurData")
omniORB.typeMapping["IDL:SDR/CapteurData:1.0"] = _0_SDR._d_CapteurData
_0_SDR.CapteurData = omniORB.newEmptyClass()
class CapteurData :
    _NP_RepositoryId = _0_SDR._d_CapteurData[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_SDR.CapteurData = CapteurData
_0_SDR._tc_CapteurData = omniORB.tcInternal.createTypeCode(_0_SDR._d_CapteurData)
omniORB.registerType(CapteurData._NP_RepositoryId, _0_SDR._d_CapteurData, _0_SDR._tc_CapteurData)

# CapteurData operations and attributes
CapteurData._d_envoyerDonnees = ((omniORB.tcInternal.tv_float, omniORB.tcInternal.tv_float, omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_boolean), (), None)

# CapteurData object reference
class _objref_CapteurData (CORBA.Object):
    _NP_RepositoryId = CapteurData._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def envoyerDonnees(self, *args):
        return self._obj.invoke("envoyerDonnees", _0_SDR.CapteurData._d_envoyerDonnees, args)

omniORB.registerObjref(CapteurData._NP_RepositoryId, _objref_CapteurData)
_0_SDR._objref_CapteurData = _objref_CapteurData
del CapteurData, _objref_CapteurData

# CapteurData skeleton
__name__ = "SDR__POA"
class CapteurData (PortableServer.Servant):
    _NP_RepositoryId = _0_SDR.CapteurData._NP_RepositoryId


    _omni_op_d = {"envoyerDonnees": _0_SDR.CapteurData._d_envoyerDonnees}

CapteurData._omni_skeleton = CapteurData
_0_SDR__POA.CapteurData = CapteurData
omniORB.registerSkeleton(CapteurData._NP_RepositoryId, CapteurData)
del CapteurData
__name__ = "SDR"

#
# End of module "SDR"
#
__name__ = "Irrigation_idl"

_exported_modules = ( "SDR", )

# The end.
