# DO NOT EDIT THIS FILE!
#
# Python module SDR generated by omniidl

import omniORB
omniORB.updateModule("SDR")

# ** 1. Stub files contributing to this module
import Irrigation_idl

# ** 2. Sub-modules

# ** 3. End
