# DO NOT EDIT THIS FILE!
#################3
# Python module SDR__POA generated by omniidl

import omniORB
omniORB.updateModule("SDR__POA")

# ** 1. Stub files contributing to this module
import Irrigation_idl

# ** 2. Sub-modules

# ** 3. End
